name: web_speisekarte
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # Dart-SDK (2.x) – passend zu Flutter 3.7.2
  sdk: ">=2.19.0 <3.0.0"
  # Flutter-SDK-Constraint (optional, aber empfohlen)
  flutter: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
